[package]
name = "intrepion-users-json-rpc-client-web-wasm-rust-yew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
